export const FETCH_CURRENCIES_PENDING   = 'FETCH_CURRENCIES_PENDING';
export const FETCH_CURRENCIES_FULFILLED = 'FETCH_CURRENCIES_FULFILLED';
export const FETCH_CURRENCIES_REJECTED  = 'FETCH_CURRENCIES_REJECTED';